### ISSUE TITLE
`AttributeError: can't set attribute` in Event_listener example, from `ctx.protocol = ssl_module.PROTOCOL_TLSv1_2`

### ISSUE THREAD

**Issue by fzeiser** [metno/python-productstatus-client#1]
Running `examples/event.py` 7f317cb4557619644a8ad55766c56c3f751e6fe4 I get following error:

``` pytb
Traceback (most recent call last):
  File "event.py", line 12, in <module>
    event_listener = api.get_event_listener()
  File "/home/fabioz/met/python-productstatus-client/productstatus/api.py", line 79, in get_event_listener
    self._event_listener = productstatus.event.Listener(str(configuration.topic), **kwargs)
  File "/home/fabioz/met/python-productstatus-client/productstatus/event.py", line 59, in __init__
    kwargs['ssl_context'] = Listener.create_security_context(ssl_verify)
  File "/home/fabioz/met/python-productstatus-client/productstatus/event.py", line 69, in create_security_context
    ctx.protocol = ssl_module.PROTOCOL_TLSv1_2
AttributeError: can't set attribute
```

Currently just testing the library on my private machine...

**Comment by fzeiser** [comment]
https://docs.python.org/3/library/ssl.html#ssl.SSLContext.protocol says that (3.6, 3.9)

> SSLContext.protocol
>     The protocol version chosen when constructing the context. This attribute is read-only.

**Comment by fzeiser** [comment]
A call like `import ssl; ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)` would work instead; but not sure what other aspects the `default_context` sets.

**Comment by fzeiser** [comment]
https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLSv1_2
> Deprecated since version 3.6: OpenSSL has deprecated all version specific protocols. Use the default protocol PROTOCOL_TLS with flags like OP_NO_SSLv3 instead.

To set the options, see also https://stackoverflow.com/questions/49765098/how-to-prevent-older-versions-of-the-tls-protocl-in-python-openssl-client

e.g. 
``` py
import ssl
context = ssl.create_default_context()
context.options |= ssl.OP_NO_TLSv1
```

**Comment by fzeiser** [comment]
So this part should probably be changed:
https://github.com/metno/python-productstatus-client/blob/afea41b9f8004205ddf2dceeb43d6259d66f83bb/productstatus/event.py#L66-L73

(+ add `python >= 3.6`?)
